### ISSUE TITLE
Faceting variables must have at least one value

### ISSUE THREAD

**Issue by rida1984** [dsurujon/ShinyOmics#12]
[wt_cecumVSLB.zip](https://github.com/dsurujon/ShinyOmics/files/4570094/wt_cecumVSLB.zip)

I am trying to visualize two rnaseq datasets. I edited exptsheet and metadata accordingly. When I ran the app, the files passed the validation step, but I get the following error:
Faceting variables must have at least one value
## I have minimal coding experience Tx##Pls find files attached
[Uploading wt_cecumVSLB.zip…]()

**Comment by dsurujon** [comment]
This is probably because your metadata table has only one column - which is something I hadn't considered.  A quick fix would be to include at least one other column on the metadata table, e.g. chromosomal position of the gene. I will also update the file validation to check the metadata tables for more than one column.
